---
rune_positions:
  column_1_x_axis_position: 1000
  column_2_x_axis_position: 1100
  column_3_x_axis_position: 1200
  rune_1_y_axis_position: 100
  rune_2_y_axis_position: 100
  rune_3_y_axis_position: 100
  rune_4_y_axis_position: 100
  rune_5_y_axis_position: 100
  rune_6_y_axis_position: 100
  rune_7_y_axis_position: 100
  rune_8_y_axis_position: 100
  rune_9_y_axis_position: 100
  rune_10_y_axis_position: 100
  rune_11_y_axis_position: 100
  rune_12_y_axis_position: 100
  rune_13_y_axis_position: 100
hotkeys:
  rune_1: 'q'
  rune_2: 'w'
  rune_3: 'e'
  rune_4: 'r'
  rune_5: 't'
  rune_6: 'y'
  rune_7: 'u'
  rune_8: 'a'
  rune_9: 's'
  rune_10: 'd'
  rune_11: 'f'
  rune_12: 'g'
  rune_13: 'h'
  pa_modifier: '<shift>'
  ra_modifier: '<ctrl>'
...