---
rune_positions:
  fusion_x_position: 1050
  fusion_y_position: 243
  fusion_all_x_position: 852
  fusion_all_y_position: 243
  normal_column_x_axis_position: 1113
  pa_column_x_axis_position: 1162
  ra_column_x_axis_position: 1213
  rune_1_y_axis_position: 341
  rune_2_y_axis_position: 378
  rune_3_y_axis_position: 418
  rune_4_y_axis_position: 456
  rune_5_y_axis_position: 495
  rune_6_y_axis_position: 535
  rune_7_y_axis_position: 572
  rune_8_y_axis_position: 612
  rune_9_y_axis_position: 649
  rune_10_y_axis_position: 685
  rune_11_y_axis_position: 726
  rune_12_y_axis_position: 766
  rune_13_y_axis_position: 801
hotkeys:
  toggle_smithmagic_hotkeys: '<alt>+<ctrl>+m' # smithmagic_manager hotkeys are turned off by default
  rune_1: 'q'
  rune_2: 'w'
  rune_3: 'e'
  rune_4: 'r'
  rune_5: 't'
  rune_6: 'y'
  rune_7: 'u'
  rune_8: 'a'
  rune_9: 's'
  rune_10: 'd'
  rune_11: 'f'
  rune_12: 'g'
  rune_13: 'h'
  pa_modifier: '<shift>'
  ra_modifier: '<ctrl>'
  fusion: '<space>'
  fusion_all: '<shift>+<ctrl>+<space>'
...